{
 "title": "Firebird",
 "tags": [
  "fb",
  "db"
 ],
 "time": { "from": "now-12h", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "data source", "query": "prometheus" },
   { "name": "interval", "label": "interval", "query": "1s,5s,1m,5m,1h,6h,1d" },
   { "name": "server", "label": "server", "query": { "query": "label_values(fb_info,instance)" } },
   {
    "name": "instance",
    "label": "instance",
    "query": {
     "query": "label_values(fb_info{instance=~\"^$server:.*$\"},instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "fb_info{instance=~\"$server:$instance\"}",
     "legendFormat": "{{instance}}"
    },
    {
     "expr": "fb_database_page_size{instance=~\"$server:$instance\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "label_replace(max_over_time(timestamp(changes(file_content_hash_crc32{path=~\"$instance.$server.*.log\"}[15m]) == 0)[7d:2m]) * 1000, \"instance\", \"$2:$1\", \"path\", \"(.+).(fb[0-9]+).*.log\")",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Checksums of backup files",
   "type": "state-timeline",
   "gridPos": { "h": 19, "w": 24, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "Backup file have been changed" } },
   "targets": [
    {
     "expr": "label_replace(last_over_time(file_content_hash_crc32{path=~\"$instance.$server.*.log\"}[$__interval]), \"instance\", \"$1\", \"path\", \"(.+).log\")",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Open connections",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 28 },
   "targets": [
    {
     "expr": "fb_open_connections{instance=~\"$server:$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Idle connections",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 28 },
   "targets": [
    {
     "expr": "fb_idle_connections{instance=~\"$server:$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Active transactions (duration > 5min)",
   "type": "state-timeline",
   "gridPos": { "h": 18, "w": 12, "x": 0, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "label_join(label_join(fb_transaction_duration_seconds{instance=~\"$server:$instance\"} > 300, \"value\", \" began with id \", \"transaction_timestamp\", \"transaction_id\"), \"value\", \" \", \"value\", \"process\", \"remote_address\")"
    }
   ]
  },
  {
   "title": "Memory used",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "fb_database_memory_used{instance=~\"$server:$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Next transaction - oldest active > 0",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 46 },
   "targets": [
    {
     "expr": "fb_next_transaction{instance=~\"$server:$instance\"} - fb_oldest_active{instance=~\"$server:$instance\"} > 0",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Active transactions (count)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 55 },
   "targets": [
    {
     "expr": "count_over_time(fb_transaction_duration_seconds{instance=~\"$server:$instance\"}[5m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Oldest active - oldest snapshot > 0",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 55 },
   "targets": [
    {
     "expr": "fb_oldest_active{instance=~\"$server:$instance\"} - fb_oldest_snapshot{instance=~\"$server:$instance\"} > 0",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Allocated pages",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 64 },
   "targets": [
    {
     "expr": "sum_over_time(fb_database_allocated_pages{instance=~\"$server:$instance\"}[5m])",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}